---
- hosts: website
  become: apps
  tasks:
    - name: Print OS info
      ansible.builtin.setup:
      register: os_info

    - name: Display OS info
      ansible.builtin.debug:
        var: os_info.ansible_facts

    - name: Install httpd package
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install httpd package
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
